export const addSymbolAction = (payload) =>({ type: 'addSymbol', payload})
export const deleteLastSymbolAction = (payload) =>({ type: 'deleteLastSymbol', payload})
export const deleteExpressionAction = (payload) =>({ type: 'deleteExpression', payload})
export const getResultAction = (payload) =>({ type: 'getResult', payload})
export const getHistoryAction = (payload) =>({ type: 'getHistory', payload})