export const addSymbolAction = (payload) =>({ type: 'addSymbol', payload})
export const deleteLastSymbolAction = (payload) =>({ type: 'deleteLastSymbol'})
export const deleteExpressionAction = (payload) =>({ type: 'deleteExpression'})
export const getResultAction = (payload) =>({ type: 'getResult'})
export const getHistoryAction = () =>({ type: 'getHistory'})
export const deleteAllAction = () =>({ type: 'deleteAll'})
export const deleteHistoryAction = () =>({ type: 'deleteHistory'})